# Site settings
title: "AI Researcher"
email: "your-email@example.com"
description: "A website for an AI researcher"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://eprifti.github.io" # the base hostname & protocol for your site
twitter_username: eprifti
github_username: eprifti

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Navigation
header_pages:
  - index.md
  - about.md
  - publications.md
  - projects.md
  - newpage.md

# Custom markdown settings
markdown: kramdown

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
